name: CI Laravel Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      # 1. Configuration de PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: pdo_mysql, mbstring, dom, fileinfo
          ini-values: post_max_size=256M, upload_max_filesize=256M
          tools: composer

      # 2. Cache des dépendances Composer
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # 3. Installation des dépendances
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # 4. Configuration de Laravel
      - name: Create .env
        run: |
          cp .env.example .env
          php artisan key:generate

      # 5. Tests
      - name: Run Tests
        env:
          DB_PORT: 3306
          DB_HOST: 127.0.0.1
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan migrate --env=testing && vendor/bin/phpunit
